#!/bin/bash
#
#  Command Line Interface to start all services associated with the Fast/Micro-RTPS tutorials
#
#  For this tutorial the commands are merely a convenience script to run docker-compose
#

set -e

stoppingContainers () {
	echo "Stopping containers"
	docker-compose -f docker-compose.yml -p fiware down
	echo "Removing volumes"
	docker volume prune --force
	echo ""
}

if (( $# != 1 )); then
    echo "Illegal number of parameters"
    echo "usage: services [create|stop|stop]"
    exit 1
fi

command="$1"
case "${command}" in
	"help")
        echo "usage: services [create|start|stop]"
        ;;
    "start")
		stoppingContainers
		echo -e "Starting two containers - \033[1;30mFast-RTPS\033[0m and \033[1;30mMicro-RTPS\033[0m."
		docker-compose -f docker-compose.yml -p fiware up -d --remove-orphans
		;;
	"stop")
		stoppingContainers
		;;
	"create")
		echo "Recreate Fast-RTPS examples"
		docker build -t fiware/fast-rtps-examples ./fast-rtps
		echo "Recreate Micro-RTPS examples"
		docker build -t fiware/micro-rtps-examples ./micro-rtps
		;;
esac